# -*- coding: utf-8 -*-
"""AI assignments

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B-Z5qeMBLIJj6JWkAivi5v8hQvQz9Zds
"""

print("hello world");